version: '3.8'

name: licenta
services:
  postgres-connectcampus:
    image: postgres:latest
    container_name: connectcampus_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      -  connectcampus-db-data:/data/postgres
      - ./configure-db.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "6433:5432"
    restart: unless-stopped

    networks:
      - webapi_network

networks:
  webapi_network:

volumes:
  connectcampus-db-data: