export const AUTH__SET_STATE = '[AUTH] SET_STATE';
export const AUTH__SET_TOKEN = '[AUTH] SET_TOKEN';
export const AUTH__SET_LOADING = '[AUTH] SET_LOADING';
export const AUTH__RESET_DATA = '[AUTH] RESET_DATA';
export const AUTH__LOGIN = '[AUTH] LOGIN';
export const AUTH__REFRESH = '[AUTH] REFRESH';
export const AUTH__LOGOUT = '[AUTH] LOGOUT';
export const AUTH__REGISTER_STUDENT = '[AUTH] REGISTER_STUDENT';
export const AUTH__REGISTER_ASSOCIATION = '[AUTH] REGISTER_ASSOCIATION';
export const AUTH__FORGOT_PASSWORD = '[AUTH] FORGOT_PASSWORD';
export const AUTH__RESET_PASSWORD = '[AUTH] RESET_PASSWORD';
export const AUTH__VERIFY_TWO_FACTOR = '[AUTH] VERIFY_TWO_FACTOR';
export const AUTH__VERIFY_EMAIL = '[AUTH] VERIFY_EMAIL';
export const AUTH__GET_ME = '[AUTH] GET_ME';

export const USER__SET = '[USER] SET';
export const USER__SET_LOADING = '[USER] SET_LOADING';
export const USER__SET_ROLE = '[USER] SET_ROLE';
export const USER__RESET = '[USER] RESET';
export const USER__FETCH = '[USER] FETCH';
export const USER__REGISTER = '[USER] REGISTER';

export const PROFILE__SET = '[PROFILE] SET';
export const PROFILE__SET_LOADING = '[PROFILE] SET_LOADING';
export const PROFILE__FETCH = '[PROFILE] FETCH';
export const PROFILE__UPDATE = '[PROFILE] UPDATE';
export const PROFILE__RESET = '[PROFILE] RESET';
export const PROFILE__SET_PAYMENT_METHOD = '[PROFILE] SET_PAYMENT_METHOD';
export const PROFILE__SAVE_PAYMENT_METHOD = '[PROFILE] SAVE_PAYMENT_METHOD';
export const PROFILE__UPLOAD_CERTIFICATE = '[PROFILE] PROFILE__UPLOAD_CERTIFICATE';
export const PROFILE__AVATAR_SET = '[PROFILE] AVATAR_SET';
export const PROFILE__UPLOAD_AVATAR = '[PROFILE] UPLOAD_AVATAR';
export const PROFILE__REMOVE_CATEGORY = '[PROFILE] REMOVE_CATEGORY';
export const PROFILE__ADD_CATEGORY = '[PROFILE] ADD_CATEGORY';

// Student constants
export const STUDENT__SET = '[STUDENT] SET';
export const STUDENT__SET_LIST = '[STUDENT] SET_LIST';
export const STUDENT__SET_LOADING = '[STUDENT] SET_LOADING';
export const STUDENT__RESET = '[STUDENT] RESET';
export const STUDENT__GET_BY_ID = '[STUDENT] GET_BY_ID';
export const STUDENT__GET_LIST = '[STUDENT] GET_LIST';
export const STUDENT__CREATE = '[STUDENT] CREATE';
export const STUDENT__UPDATE = '[STUDENT] UPDATE';
export const STUDENT__DELETE = '[STUDENT] DELETE';
export const STUDENT__UPDATE_AVATAR = '[STUDENT] UPDATE_AVATAR';
export const STUDENT__UPDATE_INTERESTS = '[STUDENT] UPDATE_INTERESTS';
export const STUDENT__SEARCH = '[STUDENT] SEARCH';

// Association constants
export const ASSOCIATION__SET = '[ASSOCIATION] SET';
export const ASSOCIATION__SET_LIST = '[ASSOCIATION] SET_LIST';
export const ASSOCIATION__SET_FEATURED = '[ASSOCIATION] SET_FEATURED';
export const ASSOCIATION__SET_LOADING = '[ASSOCIATION] SET_LOADING';
export const ASSOCIATION__RESET = '[ASSOCIATION] RESET';
export const ASSOCIATION__GET_BY_ID = '[ASSOCIATION] GET_BY_ID';
export const ASSOCIATION__GET_LIST = '[ASSOCIATION] GET_LIST';
export const ASSOCIATION__CREATE = '[ASSOCIATION] CREATE';
export const ASSOCIATION__UPDATE = '[ASSOCIATION] UPDATE';
export const ASSOCIATION__DELETE = '[ASSOCIATION] DELETE';
export const ASSOCIATION__UPDATE_LOGO = '[ASSOCIATION] UPDATE_LOGO';
export const ASSOCIATION__UPDATE_COVER = '[ASSOCIATION] UPDATE_COVER';
export const ASSOCIATION__SEARCH = '[ASSOCIATION] SEARCH';
export const ASSOCIATION__GET_FEATURED = '[ASSOCIATION] GET_FEATURED';

// Follow constants
export const FOLLOW__FOLLOW_ASSOCIATION = '[FOLLOW] FOLLOW_ASSOCIATION';
export const FOLLOW__UNFOLLOW_ASSOCIATION = '[FOLLOW] UNFOLLOW_ASSOCIATION';
export const FOLLOW__GET_FOLLOWERS = '[FOLLOW] GET_FOLLOWERS';
export const FOLLOW__GET_FOLLOWS = '[FOLLOW] GET_FOLLOWS';
// DEPRECATED: Stats calculated manually now
// export const FOLLOW__GET_STUDENT_STATS = '[FOLLOW] GET_STUDENT_STATS';
// export const FOLLOW__GET_ASSOCIATION_STATS = '[FOLLOW] GET_ASSOCIATION_STATS';
export const FOLLOW__CHECK_STATUS = '[FOLLOW] CHECK_STATUS';
export const FOLLOW__REMOVE_FOLLOWER = '[FOLLOW] REMOVE_FOLLOWER';
export const FOLLOW__GET_NOTIFICATIONS = '[FOLLOW] GET_NOTIFICATIONS';

// Event constants
export const EVENT__SET = '[EVENT] SET';
export const EVENT__SET_LIST = '[EVENT] SET_LIST';
export const EVENT__SET_FEATURED = '[EVENT] SET_FEATURED';
export const EVENT__SET_UPCOMING = '[EVENT] SET_UPCOMING';
export const EVENT__SET_CATEGORIES = '[EVENT] SET_CATEGORIES';
export const EVENT__SET_REGISTRATIONS = '[EVENT] SET_REGISTRATIONS';
export const EVENT__SET_USER_REGISTRATIONS = '[EVENT] SET_USER_REGISTRATIONS';
export const EVENT__SET_FAVORITES = '[EVENT] SET_FAVORITES';
export const EVENT__SET_LOADING = '[EVENT] SET_LOADING';
export const EVENT__RESET = '[EVENT] RESET';
export const EVENT__GET_BY_ID = '[EVENT] GET_BY_ID';
export const EVENT__GET_LIST = '[EVENT] GET_LIST';
export const EVENT__CREATE = '[EVENT] CREATE';
export const EVENT__UPDATE = '[EVENT] UPDATE';
export const EVENT__DELETE = '[EVENT] DELETE';
export const EVENT__SEARCH = '[EVENT] SEARCH';
export const EVENT__GET_CATEGORIES = '[EVENT] GET_CATEGORIES';
export const EVENT__REGISTER = '[EVENT] REGISTER';
export const EVENT__UNREGISTER = '[EVENT] UNREGISTER';
export const EVENT__GET_REGISTRATIONS = '[EVENT] GET_REGISTRATIONS';
export const EVENT__GET_USER_REGISTRATIONS = '[EVENT] GET_USER_REGISTRATIONS';
export const EVENT__ADD_TO_FAVORITES = '[EVENT] ADD_TO_FAVORITES';
export const EVENT__REMOVE_FROM_FAVORITES = '[EVENT] REMOVE_FROM_FAVORITES';
export const EVENT__GET_FAVORITES = '[EVENT] GET_FAVORITES';

// Report constants
export const REPORT__CREATE = '[REPORT] CREATE';
export const REPORT__GET_BY_ID = '[REPORT] GET_BY_ID';
export const REPORT__GET_LIST = '[REPORT] GET_LIST';
export const REPORT__UPDATE = '[REPORT] UPDATE';
export const REPORT__DELETE = '[REPORT] DELETE';
export const REPORT__GET_BY_USER = '[REPORT] GET_BY_USER';
export const REPORT__ASSIGN = '[REPORT] ASSIGN';
export const REPORT__UPDATE_STATUS = '[REPORT] UPDATE_STATUS';

// User Preferences constants
export const USER_PREFERENCES__FETCH = '[USER_PREFERENCES] FETCH';
export const USER_PREFERENCES__UPDATE = '[USER_PREFERENCES] UPDATE';

// Action type objects for createAsyncThunk
export const USER_PREFERENCES_ACTION_TYPES = {
  FETCH_USER_PREFERENCES: USER_PREFERENCES__FETCH,
  UPDATE_USER_PREFERENCES: USER_PREFERENCES__UPDATE,
};

// Authentication
export const SET_AUTH_TOKEN = '[AUTH] SET_TOKEN';
export const CLEAR_AUTH_TOKEN = '[AUTH] CLEAR_TOKEN';
export const SET_USER_DATA = '[AUTH] SET_USER_DATA';
export const CLEAR_USER_DATA = '[AUTH] CLEAR_USER_DATA';
export const LOGIN_ASYNC = '[AUTH] LOGIN_ASYNC';
export const LOGOUT_ASYNC = '[AUTH] LOGOUT_ASYNC';
export const REFRESH_TOKEN_ASYNC = '[AUTH] REFRESH_TOKEN_ASYNC';

// Events
export const SET_EVENTS = '[EVENTS] SET_EVENTS';
export const SET_SELECTED_EVENT = '[EVENTS] SET_SELECTED_EVENT';
export const SET_FEATURED_EVENTS = '[EVENTS] SET_FEATURED_EVENTS';
export const SET_UPCOMING_EVENTS = '[EVENTS] SET_UPCOMING_EVENTS';
export const SET_EVENTS_LOADING = '[EVENTS] SET_LOADING';
export const SET_EVENTS_ERROR = '[EVENTS] SET_ERROR';
export const CLEAR_EVENTS_ERROR = '[EVENTS] CLEAR_ERROR';
export const SET_EVENT_PAGINATION = '[EVENTS] SET_PAGINATION';
export const SET_EVENT_FILTERS = '[EVENTS] SET_FILTERS';
export const CLEAR_EVENT_FILTERS = '[EVENTS] CLEAR_FILTERS';

// Event Registration
export const SET_USER_REGISTRATIONS = '[EVENTS] SET_USER_REGISTRATIONS';
export const ADD_USER_REGISTRATION = '[EVENTS] ADD_USER_REGISTRATION';
export const REMOVE_USER_REGISTRATION = '[EVENTS] REMOVE_USER_REGISTRATION';
export const SET_REGISTRATION_LOADING = '[EVENTS] SET_REGISTRATION_LOADING';
export const SET_REGISTRATION_ERROR = '[EVENTS] SET_REGISTRATION_ERROR';
export const CLEAR_REGISTRATION_ERROR = '[EVENTS] CLEAR_REGISTRATION_ERROR';

// Event Favorites
export const SET_USER_FAVORITES = '[EVENTS] SET_USER_FAVORITES';
export const ADD_USER_FAVORITE = '[EVENTS] ADD_USER_FAVORITE';
export const REMOVE_USER_FAVORITE = '[EVENTS] REMOVE_USER_FAVORITE';
export const SET_FAVORITES_LOADING = '[EVENTS] SET_FAVORITES_LOADING';
export const SET_FAVORITES_ERROR = '[EVENTS] SET_FAVORITES_ERROR';
export const CLEAR_FAVORITES_ERROR = '[EVENTS] CLEAR_FAVORITES_ERROR';

// Event CRUD Operations
export const GET_EVENTS_ASYNC = '[EVENTS] GET_EVENTS_ASYNC';
export const GET_EVENT_BY_ID_ASYNC = '[EVENTS] GET_EVENT_BY_ID_ASYNC';
export const GET_EVENT_BY_SLUG_ASYNC = '[EVENTS] GET_EVENT_BY_SLUG_ASYNC';
export const GET_FEATURED_EVENTS_ASYNC = '[EVENTS] GET_FEATURED_EVENTS_ASYNC';
export const GET_UPCOMING_EVENTS_ASYNC = '[EVENTS] GET_UPCOMING_EVENTS_ASYNC';
export const CREATE_EVENT_ASYNC = '[EVENTS] CREATE_EVENT_ASYNC';
export const UPDATE_EVENT_ASYNC = '[EVENTS] UPDATE_EVENT_ASYNC';
export const DELETE_EVENT_ASYNC = '[EVENTS] DELETE_EVENT_ASYNC';

// Event Registration Operations
export const REGISTER_FOR_EVENT_ASYNC = '[EVENTS] REGISTER_FOR_EVENT_ASYNC';
export const UNREGISTER_FROM_EVENT_ASYNC = '[EVENTS] UNREGISTER_FROM_EVENT_ASYNC';
export const GET_USER_REGISTRATIONS_ASYNC = '[EVENTS] GET_USER_REGISTRATIONS_ASYNC';

// Event Favorites Operations
export const ADD_TO_FAVORITES_ASYNC = '[EVENTS] ADD_TO_FAVORITES_ASYNC';
export const REMOVE_FROM_FAVORITES_ASYNC = '[EVENTS] REMOVE_FROM_FAVORITES_ASYNC';
export const GET_USER_FAVORITES_ASYNC = '[EVENTS] GET_USER_FAVORITES_ASYNC';
export const CHECK_EVENT_REGISTRATION_STATUS_ASYNC = '[EVENTS] CHECK_EVENT_REGISTRATION_STATUS_ASYNC';
export const CHECK_EVENT_FAVORITE_STATUS_ASYNC = '[EVENTS] CHECK_EVENT_FAVORITE_STATUS_ASYNC';

// Alerts
export const SET_ALERT = '[ALERTS] SET_ALERT';
export const REMOVE_ALERT = '[ALERTS] REMOVE_ALERT';
export const CLEAR_ALERTS = '[ALERTS] CLEAR_ALERTS';
// Announcements
export const SET_ANNOUNCEMENTS = '[ANNOUNCEMENTS] SET_ANNOUNCEMENTS';
export const APPEND_ANNOUNCEMENTS = '[ANNOUNCEMENTS] APPEND_ANNOUNCEMENTS';
export const SET_CURRENT_ANNOUNCEMENT = '[ANNOUNCEMENTS] SET_CURRENT_ANNOUNCEMENT';
export const SET_ANNOUNCEMENTS_LOADING = '[ANNOUNCEMENTS] SET_LOADING';
export const SET_ANNOUNCEMENTS_ERROR = '[ANNOUNCEMENTS] SET_ERROR';
export const CLEAR_ANNOUNCEMENTS_ERROR = '[ANNOUNCEMENTS] CLEAR_ERROR';
export const SET_ANNOUNCEMENTS_PAGINATION = '[ANNOUNCEMENTS] SET_PAGINATION';
export const SET_ANNOUNCEMENTS_FILTERS = '[ANNOUNCEMENTS] SET_FILTERS';
export const CLEAR_ANNOUNCEMENTS_FILTERS = '[ANNOUNCEMENTS] CLEAR_FILTERS';

// Announcement Comments
export const SET_ANNOUNCEMENT_COMMENTS = '[ANNOUNCEMENTS] SET_COMMENTS';
export const ADD_ANNOUNCEMENT_COMMENT = '[ANNOUNCEMENTS] ADD_COMMENT';
export const UPDATE_ANNOUNCEMENT_COMMENT = '[ANNOUNCEMENTS] UPDATE_COMMENT';
export const DELETE_ANNOUNCEMENT_COMMENT = '[ANNOUNCEMENTS] DELETE_COMMENT';
export const SET_COMMENTS_LOADING = '[ANNOUNCEMENTS] SET_COMMENTS_LOADING';
export const SET_COMMENTS_ERROR = '[ANNOUNCEMENTS] SET_COMMENTS_ERROR';

// Announcement Likes
export const SET_ANNOUNCEMENT_LIKES = '[ANNOUNCEMENTS] SET_LIKES';
export const ADD_ANNOUNCEMENT_LIKE = '[ANNOUNCEMENTS] ADD_LIKE';
export const REMOVE_ANNOUNCEMENT_LIKE = '[ANNOUNCEMENTS] REMOVE_LIKE';
export const SET_LIKES_LOADING = '[ANNOUNCEMENTS] SET_LIKES_LOADING';
export const SET_LIKES_ERROR = '[ANNOUNCEMENTS] SET_LIKES_ERROR';

// Announcement Statistics
export const SET_ANNOUNCEMENT_STATISTICS = '[ANNOUNCEMENTS] SET_STATISTICS';
export const SET_STATISTICS_LOADING = '[ANNOUNCEMENTS] SET_STATISTICS_LOADING';

// Announcement CRUD Operations
export const GET_ANNOUNCEMENTS_ASYNC = '[ANNOUNCEMENTS] GET_ANNOUNCEMENTS_ASYNC';
export const GET_ANNOUNCEMENT_BY_ID_ASYNC = '[ANNOUNCEMENTS] GET_ANNOUNCEMENT_BY_ID_ASYNC';
export const CREATE_ANNOUNCEMENT_ASYNC = '[ANNOUNCEMENTS] CREATE_ANNOUNCEMENT_ASYNC';
export const UPDATE_ANNOUNCEMENT_ASYNC = '[ANNOUNCEMENTS] UPDATE_ANNOUNCEMENT_ASYNC';
export const DELETE_ANNOUNCEMENT_ASYNC = '[ANNOUNCEMENTS] DELETE_ANNOUNCEMENT_ASYNC';

// Announcement Comment Operations
export const GET_ANNOUNCEMENT_COMMENTS_ASYNC = '[ANNOUNCEMENTS] GET_COMMENTS_ASYNC';
export const CREATE_ANNOUNCEMENT_COMMENT_ASYNC = '[ANNOUNCEMENTS] CREATE_COMMENT_ASYNC';
export const UPDATE_ANNOUNCEMENT_COMMENT_ASYNC = '[ANNOUNCEMENTS] UPDATE_COMMENT_ASYNC';
export const DELETE_ANNOUNCEMENT_COMMENT_ASYNC = '[ANNOUNCEMENTS] DELETE_COMMENT_ASYNC';

// Announcement Like Operations
export const GET_ANNOUNCEMENT_LIKES_ASYNC = '[ANNOUNCEMENTS] GET_LIKES_ASYNC';
export const LIKE_ANNOUNCEMENT_ASYNC = '[ANNOUNCEMENTS] LIKE_ANNOUNCEMENT_ASYNC';
export const UNLIKE_ANNOUNCEMENT_ASYNC = '[ANNOUNCEMENTS] UNLIKE_ANNOUNCEMENT_ASYNC';

// Announcement Statistics Operations
export const GET_ANNOUNCEMENT_STATISTICS_ASYNC = '[ANNOUNCEMENTS] GET_STATISTICS_ASYNC';

